"""
Streamlit dashboard for the AI Audit Assistant.

This is a thin client: it uploads a document to the FastAPI backend (or
asks it to run a bundled sample) and renders whatever AuditResult comes
back. All audit logic lives in the backend — the frontend never computes
risk itself.

Run the backend first:
    uvicorn app.main:app --reload

Then run this:
    streamlit run frontend/streamlit_app.py
"""
import json
import sys
from pathlib import Path

import requests
import streamlit as st

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from config import API_BASE_URL  # noqa: E402

st.set_page_config(page_title="AI Audit Assistant", page_icon="🧾", layout="centered")

STATUS_ICON = {"PASS": "✅", "WARNING": "⚠️", "FAIL": "❌"}
RISK_COLOR = {"LOW RISK": "green", "MEDIUM RISK": "orange", "HIGH RISK": "red"}

#added code date 1/9/2026
JSON_TEMPLATE = {
    "vendor": "Example Vendor",
    "invoice_number": "INV-0001",
    "date": "2026-08-10",
    "payment_date": "2026-08-20",
    "amount": 10000,
    "tax": 1800,
    "total": 11800,
    "category": "Equipment",
    "notes": "Example invoice"
}

CSV_TEMPLATE = """vendor,invoice_number,date,payment_date,amount,tax,total,category,notes
Example Vendor,INV-0001,2026-08-10,2026-08-20,10000,1800,11800,Equipment,Example invoice
"""
#added code

def render_result(result: dict) -> None:
    st.markdown("## Audit Result")

    score = result["risk_score"]
    level = result["risk_level"]
    color = RISK_COLOR.get(level, "gray")

    c1, c2 = st.columns(2)
    c1.metric("Audit Risk Score", f"{score} / 100")
    c2.markdown(f"### :{color}[{level}]")

    st.progress(score / 100)
    st.caption(
        "This is a transparent, rule-derived score — not a calibrated "
        "probability of fraud. It reflects how many and which checks "
        "were not passed; see Findings below for exactly why."
    )

    st.markdown("### Findings")
    for f in result["findings"]:
        icon = STATUS_ICON.get(f["status"], "•")
        with st.expander(f"{icon} {f['title']} — {f['status']}"):
            st.write(f["detail"])
            if f["evidence"]:
                st.markdown("**Evidence:**")
                for e in f["evidence"]:
                    st.markdown(f"- **{e['label']}:** {e['value']}")

    st.markdown("### AI Audit Summary")
    source = result.get("ai_summary_source", "template_fallback")
    if source == "template_fallback":
        st.caption("Generated from findings by template (no LLM key configured).")
    else:
        st.caption("Generated by LLM from precomputed findings only.")
    st.markdown(result["ai_summary"])

    with st.expander("Extracted structured data (what the system actually used)"):
        st.json(result["extracted"])


def main() -> None:
    st.title("🧾 AI Audit Assistant")
    st.write(
        "Upload an invoice or expense report. Deterministic rules and "
        "statistical checks find issues; an LLM only explains them — "
        "it never decides risk on its own."
    )

    tab_upload, tab_samples = st.tabs(["Upload a document", "Try a sample"])

    with tab_upload:

        st.markdown("### Upload a financial document")

        st.info(
            "For the most consistent extraction, use the recommended "
            "JSON or CSV structure below."
        )

        st.markdown("#### Recommended format")

        st.write(
            "JSON or CSV using the fields shown in the templates. "
            "PDF and image files are also supported."
        )

        st.markdown("#### Supported formats")

        st.markdown(
            """
            | Format | Recommendation | Use |
            |---|---|---|
            | **JSON** | ⭐ Best | Structured invoice data |
            | **CSV** | ⭐ Best | Tabular invoice data |
            | **PDF** | Recommended | Digital invoices |
            | **PNG / JPG** | Supported | Scanned invoices |
            """
        )

        col1, col2 = st.columns(2)

        with col1:
            st.download_button(
                label="Download JSON Template",
                data=json.dumps(JSON_TEMPLATE, indent=4),
                file_name="invoice_template.json",
                mime="application/json",
            )

        with col2:
            st.download_button(
                label="Download CSV Template",
                data=CSV_TEMPLATE,
                file_name="invoice_template.csv",
                mime="text/csv",
            )

        st.markdown("#### Upload your document")

        uploaded = st.file_uploader(
            "Choose an invoice or expense document",
            type=["pdf", "csv", "json", "png", "jpg", "jpeg"],
        )

        if uploaded is not None:

            file_extension = uploaded.name.lower().split(".")[-1]

            if file_extension in ["png", "jpg", "jpeg"]:
                st.warning(
                    "Image files use OCR for extraction. "
                    "For the most reliable structured data, "
                    "JSON or CSV is recommended."
                )

            elif file_extension == "pdf":
                st.info(
                    "PDF text extraction will be used. "
                    "For the most predictable extraction, "
                    "consider using the JSON or CSV template."
                )

        if uploaded is not None and st.button("Run audit", type="primary"):
            with st.spinner("Extracting, checking rules, and generating summary..."):
                try:
                    resp = requests.post(
                        f"{API_BASE_URL}/audit/upload",
                        files={"file": (uploaded.name, uploaded.getvalue())},
                        timeout=30,
                    )
                    if resp.status_code == 200:
                        render_result(resp.json())
                    else:
                        st.error(f"Backend error ({resp.status_code}): {resp.json().get('detail')}")
                except requests.exceptions.ConnectionError:
                    st.error(
                        f"Could not reach the backend at {API_BASE_URL}. "
                        "Start it with: uvicorn app.main:app --reload"
                    )

    with tab_samples:
        try:
            samples = requests.get(f"{API_BASE_URL}/audit/samples", timeout=10).json()
        except requests.exceptions.ConnectionError:
            samples = []
            st.error(
                f"Could not reach the backend at {API_BASE_URL}. "
                "Start it with: uvicorn app.main:app --reload"
            )

        if samples:
            choice = st.selectbox("Bundled sample documents", samples)
            if st.button("Run audit on sample", type="primary"):
                with st.spinner("Running pipeline on sample document..."):
                    resp = requests.get(f"{API_BASE_URL}/audit/sample/{choice}", timeout=30)
                    if resp.status_code == 200:
                        render_result(resp.json())
                    else:
                        st.error(f"Backend error ({resp.status_code}): {resp.json().get('detail')}")


if __name__ == "__main__":
    main()
